stages:
  get_data:
    cmd: python get_data.py
    deps:
      - get_data.py
    outs:
      - dataset/test_features.csv
      - dataset/train_features.csv
      - dataset/test_labels.csv
      - dataset/train_labels.csv
  train:
    cmd: python train.py
    deps:
      - train.py
      - dataset/test_features.csv
      - dataset/train_features.csv
      - dataset/test_labels.csv
      - dataset/train_labels.csv
    metrics:
      - metrics.json:
          cache: false
    plots:
      - plot.png:
          cache: false
