name: test_gpu
on: [push]
jobs:
  GPU-Test:
    runs-on: [self-hosted,cml,gpu]
    container:
      image: fsbaader/fpii-cml:latest
      options: --gpus all
    steps:
      - uses: actions/checkout@v2
      - name: Test GPU
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## Test if nvidia is setup properly" > report.md
          CODEBLOCK="\`\`\`"
          echo "$CODEBLOCK" >> report.md
          nvidia-smi >> report.md
          echo "$CODEBLOCK" >> report.md

          echo "## Show available gpus for tensorflow." >> report.md
          python -c "import tensorflow as tf; print('List of available gpus: {}').format(tf.config.list_physical_devices('GPU'))" >> report.md

          cml-send-comment report.md
